# Generated by Django 4.2.2 on 2023-07-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='url',
        ),
        migrations.AlterField(
            model_name='travels',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
