# Generated by Django 4.2.2 on 2023-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_remove_travels_url_alter_travels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='travels',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/'),
        ),
        migrations.AddField(
            model_name='travels',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/'),
        ),
        migrations.AddField(
            model_name='travels',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/'),
        ),
        migrations.AddField(
            model_name='travels',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/'),
        ),
    ]
