# Generated by Django 4.2.2 on 2023-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_travels_image2_travels_image3_travels_image4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travels',
            options={'verbose_name': 'путешествие', 'verbose_name_plural': 'путешествия'},
        ),
        migrations.AddField(
            model_name='travels',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/', verbose_name='Картинка6'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='image',
            field=models.ImageField(upload_to='travels/images/', verbose_name='Картинка1'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/', verbose_name='Картинка2'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/', verbose_name='Картинка3'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/', verbose_name='Картинка4'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='travels/images/', verbose_name='Картинка5'),
        ),
        migrations.AlterField(
            model_name='travels',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
